import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Cart from "./components/Cart";
import NavBar from "./components/NavBar";
import "./globals.css";
import QueryClientProvider from "./providers/QueryClientProvider";
import ReduxProvider from "./redux/Provider";
import ThemeProvider from "./providers/ThemeProvider";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="light">
        <ReduxProvider>
          <QueryClientProvider>
            <ThemeProvider>
              <NavBar />
              <Cart />
              <div className="wrapper">
                <main className="pt-28 pb-16">{children}</main>
              </div>
              <Footer />
            </ThemeProvider>
          </QueryClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
